// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTItHwDeU1RjjBllOAVk0IBzATZZrbIQs',
    appId: '1:900927417626:web:8f68c77657468a4989d0a3',
    messagingSenderId: '900927417626',
    projectId: 'smartcie-e4a51',
    authDomain: 'smartcie-e4a51.firebaseapp.com',
    storageBucket: 'smartcie-e4a51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAV1HIllXDKy6YRlhcbYgfCAD-4wOIhYA',
    appId: '1:900927417626:android:dc8cd5eb5716129189d0a3',
    messagingSenderId: '900927417626',
    projectId: 'smartcie-e4a51',
    storageBucket: 'smartcie-e4a51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgVFg9iaLgBvrR3VqfewyZZC7yj_jT1E',
    appId: '1:900927417626:ios:33db3208719f095d89d0a3',
    messagingSenderId: '900927417626',
    projectId: 'smartcie-e4a51',
    storageBucket: 'smartcie-e4a51.firebasestorage.app',
    iosBundleId: 'com.example.smartmeterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfgVFg9iaLgBvrR3VqfewyZZC7yj_jT1E',
    appId: '1:900927417626:ios:33db3208719f095d89d0a3',
    messagingSenderId: '900927417626',
    projectId: 'smartcie-e4a51',
    storageBucket: 'smartcie-e4a51.firebasestorage.app',
    iosBundleId: 'com.example.smartmeterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTItHwDeU1RjjBllOAVk0IBzATZZrbIQs',
    appId: '1:900927417626:web:e7cd3e091fd4fb2489d0a3',
    messagingSenderId: '900927417626',
    projectId: 'smartcie-e4a51',
    authDomain: 'smartcie-e4a51.firebaseapp.com',
    storageBucket: 'smartcie-e4a51.firebasestorage.app',
  );
}
